### ISSUE TITLE
Error running the test

### ISSUE THREAD

**Issue by VanQz** [osrts/osrts-backend#3]
I got an error when running the test.

My system:
VM Environment (CentOS 7.3 64bit)

The Error:
[root@localhost osrts-backend]# mocha
/home/backend/osrts-backend/src/services/runners/generator-excel.js:38
  async function generateExcel(req, res, next) {
        ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/backend/osrts-backend/src/services/index.js:13:23)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/backend/osrts-backend/src/app.js:22:18)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/backend/osrts-backend/test/app.test.js:11:13)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at /usr/lib/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (native)
    at Mocha.loadFiles (/usr/lib/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/usr/lib/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/usr/lib/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
    at bootstrap_node.js:507:3

**Comment by GuillaumeDeconinck** [comment]
Hi there !
I didn't expect to see someone on this repository

I think it's related to the async/await.
I forgot to update the requirements in the package.json and in the README, but we moved to the new LTS version, aka NodeJS 8.x

I'll update those files in the next few days.

If you really need Node 6.x, I suggest that you clone the project and go back in the history before the _Added export excel_ commit.

Have a nice day !

**Comment by VanQz** [comment]
Hi,

Thanks for the quick response!
What would i need to add into the package.json?
Also NodeJS 8.x its v6.14.2 after running the node -v command right?

Thanks!

**Comment by GuillaumeDeconinck** [comment]
Nothing for you to change in the package.json.
However, if `node -v` returns you v6.14.2, you are in Node 6.
You need to update your Node version to Node 8 (https://nodejs.org/en/) or use `nvm` to keep both installations/versions (https://github.com/creationix/nvm).
